name: Signal Bot Multiple Times (Excluding Weekends)

on:
  schedule:
    - cron: '0 22 * * 1-5'    # 월~금 오전 7시 (한국시간)
    - cron: '30 0 * * 1-5'    # 월~금 오전 9시 30분 (한국시간)
    - cron: '30 5 * * 1-5'    # 월~금 오후 2시 30분 (한국시간)
    - cron: '30 6 * * 1-5'    # 월~금 오후 3시 30분 (한국시간)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pandas openpyxl

    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python main.py
